version: '3'

services:
  # FastAPI app service
  app:
    build: .
    ports:
      - "6969:6969"
    volumes:
      - .:/app
    depends_on:
      - cassandra
    environment:
      - CASSANDRA_HOST=cassandra
      - CASSANDRA_KEYSPACE=messenger
    command: uvicorn app.main:app --host 0.0.0.0 --port 6969 --reload
  
  # Cassandra database
  cassandra:
    image: cassandra:latest
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MessengerCluster
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
      test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
      interval: 15s
      timeout: 10s
      retries: 10

volumes:
  cassandra_data: 